data_root: "dataset/rgbd_dataset_freiburg3_sitting_halfsphere"
data_type: "fr3"
near: 0.1
far: 4.0
vol_bounds: [-5.0, 5.0, -4.0, 2.0, -2.0,4.0]
voxel_size: 0.05
n_pyramids: 3
n_iters: [6, 3, 3]
dampings: [1.0e-3, 1.0e-3, 1.0e-2]
n_steps: 192
fuse_color: false

